# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Code quality check

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - tests/**
      - gloe/**
      - '.github/workflows/code-quality.yml'
  pull_request:
    branches: [ "develop", "main" ]
    types: [opened, reopened]
    paths:
      - tests/**
      - gloe/**
      - '.github/workflows/code-quality.yml'

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: flake8 Lint
      run: |
        flake8 gloe tests
  black-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
    - name: black Lint
      run: |
        black --check gloe tests
        
